In [25]:
import cvxpy as cp
import numpy as np

# Problem data.
n = 5
w = numpy.random.randn(n)
#w = [-1, -1, -3, -2, -4]
print(w)
b = numpy.random.randn(1)
# Construct the problem.
x = cp.Variable(n)
objective = cp.Maximize(w*x)
ones = np.ones(n)
constraints = [0 <= x, x <= 1, ones * x == 1]
prob = cp.Problem(objective, constraints)

print("Optimal value", prob.solve())
print("Optimal var")
print(x.value) # A numpy ndarray.

[-0.18656977 -0.10174587  0.86888616  0.75041164  0.52946532]
Optimal value 0.8688875219365219
Optimal var
[-6.92274780e-07 -2.73989197e-07  1.00000113e+00  1.41141419e-06
 -1.57780258e-06]


In [31]:
n = 5
np.random.seed(1)
ones = np.ones(n)
Q = np.random.randn(n, n)
Q = Q.T @ Q
print(Q)

# Define and solve the CVXPY problem.
x = cp.Variable(n)
prob = cp.Problem(cp.Minimize((1/2)*cp.quad_form(x, Q)),
                 [ones * x == 1, x >= 0])
prob.solve()
# Print result.
print("\nThe optimal value is", prob.value)
print("A solution x is")
print(x.value)


[[12.49446123 -9.09185616  0.39584582 -3.63816679  2.00481704]
 [-9.09185616  9.0029176   0.84261434  2.57220296 -2.36951023]
 [ 0.39584582  0.84261434  2.54585543  0.86366923 -0.33223406]
 [-3.63816679  2.57220296  0.86366923  1.65482792 -0.96626539]
 [ 2.00481704 -2.36951023 -0.33223406 -0.96626539  3.24776411]]

The optimal value is 0.07182714880177384
A solution x is
[2.40534147e-01 1.75665119e-01 9.52065511e-23 4.31506099e-01
 1.52294635e-01]


In [6]:
ones = np.ones(n)
ones * x

array([1., 1., 1., 1., 1.])

In [7]:
import cvxpy as cp

# Create two scalar optimization variables.
x = cp.Variable()
y = cp.Variable()

# Create two constraints.
constraints = [x + y == 1,
               x - y >= 1]

# Form objective.
obj = cp.Minimize((x - y)**2)

# Form and solve problem.
prob = cp.Problem(obj, constraints)
prob.solve()  # Returns the optimal value.
print("status:", prob.status)
print("optimal value", prob.value)
print("optimal var", x.value, y.value)

status: optimal
optimal value 1.0
optimal var 1.0 1.570086213240983e-22
